runtime: python39

env_variables:
  PORT: 8080

# Cloud Run configuration
automatic_scaling:
  min_instances: 0
  max_instances: 100

resources:
  cpu: 1
  memory_gb: 0.5

# Health check
readiness_check:
  path: "/health"

liveness_check:
  path: "/health"