apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gymnastics-ai-v2
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/buildpacks/builder
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi