name: Deploy Legal Documents to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  # 手動実行を許可
  workflow_dispatch:

# GitHubトークンの権限設定
permissions:
  contents: read
  pages: write
  id-token: write

# 同時実行制御
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Pages deployment permissions
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4